name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - run: docker-compose up --no-start 
    - run: docker-compose run -d postgres 
    - run: docker-compose run -d main 
    - name: Test
      run: docker-compose run test

